max_jobs: 1

environment:
  COVERALLS_REPO_TOKEN:
    secure: FLG2WTxc1Gvrikrvj/UXnb9IAklUhPKGYV5pxOzlwsOWGQBiiEigRnyWCvCc2Zga
  MYGET_TOKEN:
    secure: yP12k1vrHJyValU1UWnW3NySjKfXlRomR8p4qqmYs26FDztsGMlCQeT5jdCVHlz6
  CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: "true"

image: Visual Studio 2022

cache:
  - '%LocalAppData%\NuGet\v3-cache'

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

install:
  - cmd: dotnet tool restore

build_script:
  - cmd: dotnet cake --target=Full

test: false

artifacts:
  - path: outputs\*.nupkg
    name: packages
    type: NuGetPackage
  - path: outputs\*.snupkg
    name: symbols
    type: NuGetPackage
  - path: outputs\tests\report
    name: report
    type: Zip


deploy:
  - provider: Environment
    name: NuGet
    on:
      branch:
        - master
        - main
      appveyor_repo_tag: true
  - provider: Environment
    name: GitHub Packages - Kralizek
    on:
      branch:
        - master
        - main
      appveyor_repo_tag: true
  - provider: NuGet
    server: https://www.myget.org/F/kralizek/api/v2/package
    api_key:
      secure: SxuPZ1GdSw4IgdN1KHN9Ky36oUY5ZRT0ZZXd1BdDr+GgktRazqBz6dLcjA56++X/
    artifact: packages